displayName: Dynamic Security Logger
type: middleware
import: github.com/HaeMeto/Traefik-Dynamic-Logger
summary: Lightweight dynamic middleware: log metadata/headers/body (size-limited),send to external API, local TTL block, and dynamic deny lists (IP/country/email) via Traefik dynamic config or remote list sync.
testData:
  apiEndpoint: "http://security-api:8000"
  blockTTL: 300
  maxBodyBytes: 65536
  pathPrefix: ""
  extraHeaders: ""
  denyIPs: ["1.2.3.4"]
  denyCountries: ["RU","CN"]
  denyEmailDomains: ["spam.com","bad.tld"]
  emailHeaders: ["X-Email","X-Forwarded-Email"]
  countryHeader: "X-Sec-Country"
  listURL: "http://security-api:8000/lists"
  refreshSeconds: 60
